language: csharp
solution: Project1.sln
deploy:
  provider: pages
  skip-cleanup: true
  github-token: 3B_0mGFmedj1oY389LowQQ  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
install:
  - nuget restore Project1.sln
matrix:
  include:
    - dotnet: 1.1.5
      mono: none
      env: DOTNETCORE=1  # optional, can be used to take different code paths in your script
    - mono: latest
script:
  - dotnet restore
  - xbuild /p:Configuration=Release Project1.sln
